schema_version = "1.0.0"

id = "aperturia_fx_lite"
version = "1.0.2"
name = "Aperturia FX Lite"
tagline = "Fast lens effect node for Compositor"
maintainer = "Arvo Andre Radik"
type = "add-on"
blender_version_min = "4.5.0"
license = ["SPDX:GPL-3.0-or-later"]
